
spring:
  profiles:
    active: mysql




---

spring:
  profiles:
    active: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root_pw1234!#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        show_sql: true
        format_sql: true
  batch:
    jdbc:
      initialize-schema: always
    job.enabled: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

